import Head from "next/head";
import HomePage from "../components/home/HomePage";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Disxtion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </div>
  );
}
