import Head from 'next/head'
import HomePage from '../components/home/HomePage'
import Script from 'next/script'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Disxtion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      
    
        <HomePage />
        <Script src='https://unpkg.com/flowbite@1.5.3/dist/flowbite.js' />
     


    </div>
  )
}
